BC-001:
	g++ addcustomer.cpp
	./a.out
BC-002:
	g++ deletecustomer.cpp
	./a.out
BC-003:
	g++ modifycust.cpp
	./a.out
BC-004:
	g++ transaction_admin.cpp
	./a.out
BC-005:
	g++ transaction_admin.cpp
	./a.out
BC-006:
	g++ query.cpp
	./a.out
CU-001:
	g++ customerdetails.cpp
	./a.out
CU-002:
	g++ transaction_user.cpp
	./a.out
CU-003:
	g++ customerquery.cpp
	./a.out
AA-001:
	g++ login.cpp
	./a.out